#!/bin/sh
# Copyright 2017, Jeffrey E. Bedard
NAMES='ALN CHA CHT CPL CNL'
NAMES="$NAMES CS_ALT_G1 CS_ALT_G2 CS_ALT_G3 CS_G0 CS_G1 CS_G2 CS_G3"
NAMES="$NAMES CUB CUD CUF CUP CUU DA DCH DL DSR DWL ECH"
NAMES="$NAMES ED EL ELR ENTGM52 EXTGM52 HOME HPA HPR HTS HVP ICH"
NAMES="$NAMES ID IL IND LL MC NEL PAM PM PNM RC REQTPARAM RESET RI"
NAMES="$NAMES RIS RQM S7C1T S8C1T SAVEPM SBGOTO SBSWITCH SC SD SET"
NAMES="$NAMES SELINSRT SGR SS2 SS3 ST STBM SU SWL TBC TXTPAR"
NAMES="$NAMES VPA VPR"
NOLOG='CHAR STRING'
STUBS='APC DHLT DHLB EPA OSC SOS SPA'
OUT=cases.c
rm -f $OUT
for NAME in $NAMES; do
	NAME="JBXVT_TOKEN_${NAME}"
	echo "case $NAME:\n\tLOG(\"$NAME\");" >> $OUT
	echo "\tjbxvt_handle_${NAME}(xc, &token);\n\tbreak;" >> $OUT
done
for NAME in $NOLOG; do
	NAME="JBXVT_TOKEN_${NAME}"
	echo "case $NAME:\n\tjbxvt_handle_${NAME}(xc, &token);\n\tbreak;" >> $OUT
done
for STUB in $STUBS; do
	STUB="JBXVT_TOKEN_${STUB}"
	echo "case $STUB:" >> $OUT
	echo "\tLOG(\"FIXME: $STUB not implemented\");\n\tbreak;" >> $OUT
done
