// Copyright 2016, Jeffrey E. Bedard
#ifndef JBXVT_JBXVTSELECTIONUNIT_H
#define JBXVT_JBXVTSELECTIONUNIT_H

//  The current selection unit
enum JBXVTSelectionUnit {
	JBXVT_SEL_UNIT_CHAR,
	JBXVT_SEL_UNIT_WORD,
	JBXVT_SEL_UNIT_LINE
};

#endif//!JBXVT_JBXVTSELECTIONUNIT_H
