.TH jbxvt 1 "17 SEP 2016"

.SH NAME
jbxvt \- minimalistic terminal emulator

.SH SYNOPSIS
.I jbxvt \-[B:b:C:c:D:d:eF:f:hvR:S:s]

.SH DESCRIPTION
Jbxvt is a minimalistic emulator of the xterm terminal emulator for XCB.
Jbxvt implements many vt100 control sequences, as well as xterm features.
Features include mouse support, color support, scrollback history,
and utmp entry management.  It also features many code cleanups and a small
memory footprint.  

.SH OPTIONS
.IP "\fB-B\fP \fIfont\fP
Set font
.IP "\fB-b\fP \fIcolor\fP
Set background color
.IP "\fB-C\fP \fIcolumns\fP
Set number of columns
.IP "\fB-D\fP \fIdisplay\fP
Set display string
.IP "\fB-d\fP \fIscreen\fP
Set display screen

.SH ENVIRONMENT
.IP SHELL
Define the program executed by default.

