// Copyright 2017, Jeffrey E. Bedard
#ifndef JBXVT_JBXVTKEYSTRINGS_H
#define JBXVT_JBXVTKEYSTRINGS_H
/* Structure used to describe the string generated by a function key, keypad
 * key, etc.  */
struct JBXVTKeyStrings {
	uint8_t ks_type;	// the way to generate the string (see below)
	uint8_t ks_value;	// value used in creating the string
};
#endif//!JBXVT_JBXVTKEYSTRINGS_H
