#!/bin/sh
# Copyright 2016, Jeffrey E. Bedard

echo 9-bit rgb mode
echo -n '\23338;2;0;255;0m'
echo -n 'fg\t'
echo -n '\2330m'
echo -n '\23348;2;0;0;255m'
echo -n 'bg\t'
echo '\2330m'

exit
echo rgb mode
echo -n '\23338;2;225;1;50m'
echo -n 'fg\t'
echo -n '\2330m'
echo -n '\23348;2;1;20;255m'
echo -n 'bg\t'
echo '\2330m'

exit
echo index mode
echo -n '\23338;5;55m'
echo -n 'fg\t'
echo -n '\2330m'
echo -n '\23348;5;34m'
echo -n 'bg\t'
echo '\2330m'
echo

