'\" t
.\" @(#)xvt.1	1.2 16/11/93 (UKC)
.TH XVT 1 "10 February 1992"
.UC
.SH NAME
xvt \- VT100 emulator for the X window system
.SH SYNOPSIS
\fBxvt\fP [ \fIoptions\fP ]
.SH DESCRIPTION
\fIXvt\fP is a VT100 terminal emulator for X.  It is intended as a
replacement for \fIxterm\fP(1) for users who do not require the more
esoteric features of \fIxterm\fP.  Specifically \fIxvt\fP does not
implement the Tektronix 4014 emulation, session logging and toolkit
style configurability.  As a result, \fIxvt\fP uses much less swap
space than \fIxterm\fP \- a significant advantage on a machine serving
many X sessions.
.SH OPTIONS
The options supported by \fIxvt\fP (which, with the exception of
\fB-msg\fP, are a subset of those supported by \fIxterm\fP) are listed
below.  Most command line arguments have X resource equivalents and
these are listed in the following table.
.IP "\fB-e\fP \fIcommand\fP [ \fIarguments\fP ]"
Run the command with its command line arguments in the \fIxvt\fP
window.  If this option is used, it must be the last on the command
line.  If there is no \fB-e\fP option then the default is to run the
program specified by the SHELL environment variable or, failing that,
\fIcsh\fP(1).  This option also causes the window title and icon name
to be set to the name of the program being executed if the are not
overwritten by a more specific option.
.IP "\fB-display\fP \fIdisplay-name\fP"
Attempt to open the \fIxvt\fP window on the named X display.  In the
absence if this option, the display specified by the DISPLAY
environment variable is used.
.IP "\fB-geometry\fP \fIwindow-geometry\fP
Create the window with the specified X window geometry.
.IP "\fB-background\fP \fIcolor\fP
Use the specified color as the window's background color.
.IP "\fB-bg\fP \fIcolor\fP
Same as \fB-background\fP.
.IP "\fB-foreground\fP \fIcolor\fP
Use the specified colour as the window's foreground color.
.IP "\fB-fg\fP \fIcolor\fP
Same as \fB-foreground\fP.
.IP "\fB-cr\fP \fIcolor\fP
Set the color used for the text cursor.
.IP "\fB-bw\fP \fInumber\fP
Set the window border width to \fInumber\fP pixels.  Many window managers
ignore existing window borders and construct their own and so, if you are
using such a window manager, this option will be ignored.
.IP "\fB-bd\fP \fIcolor\fP
Set the border color.  As with border width, this option will usually be
disregarded with respect to the window's outer border.  It does, however,
set the color of the line separating the scroll bar from the main part of the
window.
.IP "\fB-font\fP \fIfontname\fP
Set the main text font used by \fIxvt\fP.
.IP "\fB-fn\fP \fIfontname\fP
Same as \fB-font\fP.
.IP "\fB-fb\fP \fIfontname\fP
Set the font used for the vt100 bold rendition style.  If this option
is not set then \fIxvt\fP will render in bold by overprinting
the normal font.
.IP "\fB-name\fP \fIname\fP"
Set the name that is used when looking up X resource values for this
instance of \fIxvt\fP.  This option also sets the icon name and window
title unless they are set explicitely.
.IP "\fB-title\fP \fItext\fP
Set the string that is displayed in the window's title bar if it has one.
.IP "\fB-T\fP \fItext\fP
Same as \fB-title\fP
.IP "\fB-n\fP \fItext\fP
Set the name that will be used to label the window's icon or displayed in
an icon manager window.  This option also sets the window's title unless
it is set expicitely.
.IP "\fB-sl\fP \fInumber\fP
Set an upper bound for the number of lines that will be saved when they
have scrolled off the top of the window.
.IP "\fB-sb\fP
Start up with the scrollbar visible.  The scrollbar can be displayed or
hidden at any time simply by holding down the CONTROL key on the keyboard
and pressing any mouse button.  The visibility of the scrollbar does
not determine whether scrolled text is saved or not \- as with \fIxterm\fP,
text scrolled off the top of the window is always saved up to the current
maximum number of lines.
.IP "\fB-rw\fP
Enable reverse wrapping of the cursor so that, for example, lines typed
to a shell that are longer than the width of the screen can be edited.
This is the same as the \fIxterm\fP reverse wrap option.
.IP "\fB-cc\fP \fIstring\fP
Input or modify the character classes that are used to determine what is
a word when a double click is used to select a word of displayed text.
This is identical to the same option in \fIxterm\fP \- see the xterm
manual page for a description of the syntax of \fIstring\fP.
.IP "\fB-iconic\fP
Start up with the window already iconized.
.IP "\fB-msg\fP
Enable messages to the terminal window from programs like \fIwrite\fP(1).  
By default, \fIxvt\fP windows have messages disabled.  Executing an
\fIxvt\fP with the \fB-msg\fP option has the same effect as running it
normally and then executing the command \fImesg y\fP to enable messages.
.IP \fB-8\fP
Treat characters as having eight bits \- this is the default.  When in
eight bit mode, \fIxvt\fP displays eight bit characters and pressing a
keyboard key with the \fIMeta\fP key held down generates the character
code with the MSB set.
.IP \fB-7\fP
Treat characters as having seven bits.  In this mode, each character
is stripped to seven bits before it is displayed and pressing a keybaord
key with the \fIMeta\fP key held down causes the normal character to be
preceeded by the Escape character.
.IP \fB-ls\fP
Run a login shell.  This option causes \fIxvt\fP to execute its shell
with a name beginning with `-'.  In the case of \fIcsh\fP(1) this results
in the \fI.login\fP and \fI.logout\fP files being interpreted at the
start and end of the session.
.IP "\fB-sf\fP
Enable Sun function key escape codes.  The default is standard \fIxterm\fP
compatible function codes.
.IP \fB-rv\fP
Run in reverse video \- that is, exchange the foreground and background
colors.  This option has no effect if either the foreground ar background
color is set explicitely.
.IP \fB-C\fP
Connect this terminal to the system console.  This option is only implemented
for SunOS 4 and for a user who has read and write access to /dev/console.
.IP \fB-console\fP
Same as \fB-C\fP.
.SH X RESOURCES
Almost all the command line options have X resource counterparts and
these are listed in the following table.  Like \fIxterm\fP, \fIxvt\fP
uses the class name \fIXTerm\fP and so resource options set for
\fIXTerm\fP will work for both \fIxterm\fP and \fIxvt\fP windows.
.sp
.\" troff version of table
.if n .ig IG
.TS
center box tab(/) ;
cb s s
c | c s
c | c c
l | l | l .
Command line options and X resources
_
/X resource
Command line/Instance/Class
=
-background or -bg/background/Background
-bd/borderColor/BorderColor
-bw/borderWidth/BorderWidth
-C or -console/\fINone\fP/\fINone\fP
-cc/charClass/CharClass
-cr/cursorColor/CursorColor
-display/\fINone\fP/\fINone\fP
-e/\fINone\fP/\fINone\fP
-fb/boldFont/BoldFont
-font or -fn/font/Font
-foreground or -fg/foreground/Foreground
-geometry/geometry/Geometry
-iconic/iconic/Iconic
-ls/loginShell/LoginShell
-msg/messages/Messages
-n/iconName/IconName
-name/\fINone\fP/\fINone\fP
-rv/reverseVideo/ReverseVideo
-rw/reverseWrap/ReverseWrap
-sb/scrollBar/ScrollBar
-sf/sunFunctionKeys/SunFunctionKeys
-sl/saveLines/SaveLines
-title or -T/title/Title
-8 (on) and -7 (off)/eightBitInput/EightBitInput
.TE
.IG
.\" nroff version of table
.if t .ig IG
.TS
center tab(/) ;
cb s s
c c s
c c c
l l l .
Command line options and X resources
_
/X resource
Command line/Instance/Class
=
-background or -bg/background/Background
-bd/borderColor/BorderColor
-bw/borderWidth/BorderWidth
-C or -console/-/-
-cc/charClass/CharClass
-cr/cursorColor/CursorColor
-display/-/-
-e/-/-
-fb/boldFont/BoldFont
-font or -fn/font/Font
-foreground or -fg/foreground/Foreground
-geometry/geometry/Geometry
-iconic/iconic/Iconic
-ls/loginShell/LoginShell
-msg/messages/Messages
-n/iconName/IconName
-name/-/-
-rv/reverseVideo/ReverseVideo
-rw/reverseWrap/ReverseWrap
-sb/scrollBar/ScrollBar
-sf/sunFunctionKeys/SunFunctionKeys
-sl/saveLines/SaveLines
-title or -T/title/Title
-8 (on) and -7 (off)/eightBitInput/EightBitInput
.TE
.IG
.SH NAMES TITLES AND ICON NAMES
One occasionally confusing aspect of \fIxvt\fP and other X applications
is the collection
of names that an application window can have and the relationship
between the names and the command line options used to set them.  This
section attempts to make the situation a bit clearer in the case of \fIxvt\fP.
.LP
In fact, each terminal window has three names, its resource name, its
title and its icon name.  These three names are distinct and have
different functions, although they usually have the same value.  The
resource name is the command name used to identify X resource options
in the resources database, The title is the text that is displayed in
the title bar, if there is one, and the icon name is the name that
appears in the window's icon or represents it in the icon manager
window.
.LP
The rule about which option sets which name is that \fB-name\fP and \fB-e\fP
set both the title and the icon name in addition to their main function
and \fB-n\fP sets the title as well as the icon name.  Conflicts are
resolved by giving the options priorities which are, in increasing
order, \fB-e\fP, \fB-name\fP, \fB-n\fP and \fB-title\fP.  Hence, for
example, \fB-e\fP only sets the title if none of the other options is
used.
.SH THE SCROLL BAR
Lines of text that scroll off the top of the \fIxvt\fP window are saved
automatically (up to a preset maximum number) and can be viewed by
scrolling them back into the window with the scrollbar.  The scrollbar
itself can be displayed or hidden by clicking any mouse button in the
window while holding down the CONTROL key on the keyboard.  When using
the scrollbar, the left and right mouse buttons are used for scrolling
by a few lines at a time and the middle button is used for continuous
scrolling.  To use the middle button, press it in the scroll bar and
hold it down.  the central shaded part of the scrollbar will then
attach itself to the cursor and can be slid up or down to show
different parts of the sequence of saved lines.  When scrolling with
the left and right buttons, the left button is used to scroll up and
the right is used to scroll down.  Assuming that there are enough
hidden lines, the distance scrolled with either button is equal to the
number of lines between the cursor and the top of the window.  Hence,
pressing the left cursor opposite a line of text will result in that
line being moved to be the top of the window and pressing the right
button will cause the top line to be moved down so that it is opposite
the cursor.
.SH TEXT SELECTION AND INSERTION
\fIXvt\fP uses the same kind of text selection and insertion mechanism
as \fIxterm\fP.  Pressing and releasing the middle mouse button in an
\fIxvt\fP window causes the current text selection to be inserted as if
it had been typed on the keyboard.  For the insertion to take place,
both the button press and the button release need to be done with the
cursor in the \fIxvt\fP window.
.LP
The left and right mouse buttons are used to select text, with the left
button being used to start a selection and the right button being used
to modify an existing selection.  Any continuous block of displayed
text can be selected.  If both ends of the text block are visible in
the window then the easiest way to select it is to position the cursor
at one end and press the left mouse button, then drag the cursor to the
other end with the button held down before releasing the button.  If
the block is larger than the window then you must first use the left
mouse button to select one end, then use the scroll bar to scroll the
other end into view and finally use the right mouse button to extend
the selection.  The effect of pressing the right mouse button is to
move the nearest end of the current selection to the current cursor
position.
.LP
The other way to make selections in xvt is to use double and triple
clicks of the left mouse button with a double click selecting a
word and a triple click selecting a whole line.  For this purpose,
a word is a sequence of characters in the same class.  The default
character classes are:
.IP + 3
the upper and lower case letters, digits and '_' (underscore) all in one class;
.IP +
the white space characters all in one class;
.IP +
each of the remaining punctuation characters in a class by itself.
.LP
If you want to change the character classes so that, for example, you
can select a UNIX pathname or a mail address in one double click, then
you can do so by using the \fB-cc\fP command line option or the
\fIcharClass\fP X resource.  Multiple clicking can be combined with
dragging to select a sequence of consecutive words or lines.
.LP
Although \fIxvt\fP essentially mimics the behaviour of \fIxterm\fP in
its support of text selection and insertion, there are a couple of
minor differences:
.IP + 3
\fIxvt\fP respects TAB characters in selected text and does not automatically
convert them into spaces as does \fIxterm\fP;
.IP +
\fIxvt\fP will let you abort a text insertion if you realise you have made a mistake
before releasing the middle mouse button.
.SH BUGS
Pasting very large quantities of text does not work.
.SH AUTHOR
John Bovey, University of Kent, 1992 and 1993.
